### PR TITLE
create SwiftRegex.framework target to allow inclusion in other projects

### PR DESCRIPTION
**Pull request by DanielAsher**
I've added a framework target to allow SwiftRegex to work in my workspace and projects. Please review and check!

### CODE REVIEW

**Comment by johnno1962** [comment]
Sounds good to me. Thanks!

**Comment by johnno1962** [comment]
Hi Daniel, I’ve merged this pull request but if I “download zip” from github and try to test it "out of the box”  it doesn't work. Can you look into what the problem is please? It seems to be trying to test twice!

**Comment by johnno1962** [comment]
I’ve backed this PR out for now as it was causing tests to fail. Putting one file in a framework might have been overkill anyway..

**Comment by DanielAsher** [comment]
hi John,

I should have been more thorough. I will look at this again as putting it
into a framework is a good way to use it with playgrounds and the component
may grow :)

**Pull request merged**
